@startuml Activity

start

:Зайти на сайт;
:Поиск автомобиля;
:Фильтрация по критериям;
:Выбор автомобиля;
:Просмотр деталей;

if (Хочет забронировать?) then (Да)
  :Бронирование автомобиля;
  if (Хочет арендовать?) then (Да)
    :Оформление аренды;
    :Завершение аренды;
  else (Нет)
    :Отмена бронирования;
  endif
else (Нет)
  :Возврат к списку авто;
endif

stop

@enduml