@startuml Class

' ======= MODEL =======
package "Model" {
  class Car {
    +Id: Guid
    +Brand: string
    +Model: string
    +Description: string
    +EngineCapacity: float
    +EnginePower: int
    +EngineType: EngineTypes
    +PriceForOneDay: decimal
    +CompanyId: Guid
  }

  class Company {
    +Id: Guid
    +Name: string
    +PhoneNumber: string
    +Email: string
    +CarIds: List<Guid>
  }

  class Rent {
    +Id: Guid
    +UserId: Guid
    +CarId: Guid
    +CompanyId: Guid
    +StartRent: DateTime
    +EndRent: DateTime
  }

  class User {
    +Id: Guid
    +Name: string
    +Email: string
    +Password: string
    +Role: string
  }

  Car --> EngineTypes
  Car --> Company : CompanyId
  Company --> Car : CarIds
  Rent --> Car
  Rent --> Company
  Rent --> User
}

package "DTOs"{
  class UserDto
  class CarDto
  class CompanyDto
  class RentDto

  UserDto --> User
  CarDto --> Car
  CompanyDto --> Company
  RentDto --> Rent

}
' ======= SERVICE =======
package "Service" {
  interface IUserService
  class UserService
  UserService ..|> IUserService

  interface ICarService
  class CarService
  CarService ..|> ICarService

  interface ICompanyService
  class CompanyService
  CompanyService ..|> ICompanyService
}

' ======= CONTROLLER =======
package "Controller" {
  class UsersController
  class CarsController
  class CompaniesController

  UsersController --> IUserService
  CarsController --> ICarService
  CompaniesController --> ICompanyService
}

' ======= PERSISTENCE =======
package "Persistence" {
  ' Базовый интерфейс без generic
  interface IRepository

  interface ICarRepository
  interface IUserRepository
  interface ICompanyRepository

  class CarRepository
  class UserRepository
  class CompanyRepository

  class AppDbContext
  class CarConfiguration
  class UserConfiguration
  class CompanyConfiguration

  ' Связи без <T>
  ICarRepository --|> IRepository
  IUserRepository --|> IRepository
  ICompanyRepository --|> IRepository

  CarRepository ..|> ICarRepository
  UserRepository ..|> IUserRepository
  CompanyRepository ..|> ICompanyRepository

  CarRepository --> AppDbContext
  UserRepository --> AppDbContext
  CompanyRepository --> AppDbContext

  AppDbContext --> CarConfiguration
  AppDbContext --> UserConfiguration
  AppDbContext --> CompanyConfiguration
}

' ======= СВЯЗИ между слоями =======
UserService --> IUserRepository
CarService --> ICarRepository
CompanyService --> ICompanyRepository

@enduml